/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import("element-plus/es")["ElIcon"]
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IEpBrush: typeof import('~icons/ep/brush')['default']
    IEpInfoFilled: typeof import("~icons/ep/info-filled")["default"]
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpSuccessFilled: typeof import("~icons/ep/success-filled")["default"]
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    IEpWarningFilled: typeof import("~icons/ep/warning-filled")["default"]
    IEpWarnTriangleFilled: typeof import("~icons/ep/warn-triangle-filled")["default"]
    LanguageSwitcher: typeof import('./../components/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./../components/ThemeSwitcher.vue')['default']
  }
}
